import type { Config } from "tailwindcss";

/**
 * Pawside design tokens.
 *
 * Every color below is derived from two anchors sampled directly out of the
 * official logo artwork (scripts/sample-logo.mjs):
 *
 *   navy.900  #011C35   the linework of the dog + cat and the wordmark
 *   mint.500  #36CEC1   the heart arc, the paw accent, the "PET SERVICES" rule
 *
 * Ramps were generated by scripts/build-ramps.mjs. Light navy steps crush
 * saturation so they read as paper and slate — not sky-blue chrome. Mint is
 * the only chromatic accent: hairlines, eyebrows, small states, never large fills.
 */
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx,mdx}",
    "./components/**/*.{ts,tsx}",
    "./data/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        navy: {
          50: "#F5F5F6",
          100: "#E9EAEB",
          200: "#D3D6DA",
          300: "#B0B8BF",
          400: "#788A9C",
          500: "#4A6782",
          600: "#294E70",
          700: "#113A5F",
          800: "#05294A",
          900: "#011C35",
          950: "#01101E",
        },
        mint: {
          50: "#F3F9F8",
          100: "#E5F3F2",
          200: "#CAEAE7",
          300: "#A3E0DB",
          400: "#6CD5CC",
          500: "#36CEC1",
          600: "#2AACA1",
          700: "#21877F",
          800: "#1A665F",
          900: "#154C47",
          950: "#0C2C29",
        },
        // Warm-neutral grays carrying a whisper of the brand hue.
        sand: {
          50: "#FBFBFB",
          100: "#F5F6F7",
          200: "#EBEEEF",
          300: "#D9E0E2",
          400: "#AEBBC2",
          500: "#8297A1",
          600: "#617984",
          700: "#4A5F68",
          800: "#34444B",
          900: "#212C31",
          950: "#12191C",
        },
        cream: "#FCFBF9",
        canvas: "#F6F5F3",
      },
      fontFamily: {
        // Wired to next/font in app/layout.tsx.
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "var(--font-sans)", "ui-sans-serif", "sans-serif"],
      },
      fontSize: {
        // Display scale: tight tracking + leading for confident headlines.
        "display-xs": ["1.75rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "display-sm": ["2.25rem", { lineHeight: "1.14", letterSpacing: "-0.022em" }],
        "display-md": ["2.875rem", { lineHeight: "1.08", letterSpacing: "-0.025em" }],
        "display-lg": ["3.5rem", { lineHeight: "1.04", letterSpacing: "-0.028em" }],
        "display-xl": ["4.25rem", { lineHeight: "1.02", letterSpacing: "-0.03em" }],
        "display-2xl": ["5.25rem", { lineHeight: "0.98", letterSpacing: "-0.032em" }],
      },
      borderRadius: {
        // Rounded, not bubbly: buttons 12, cards 20, feature containers 28.
        button: "12px",
        card: "20px",
        panel: "28px",
        feature: "32px",
      },
      boxShadow: {
        hairline: "0 0 0 1px rgba(1, 28, 53, 0.06)",
        soft: "0 1px 2px rgba(1, 28, 53, 0.04), 0 8px 24px -12px rgba(1, 28, 53, 0.10)",
        card: "0 1px 2px rgba(1, 28, 53, 0.04), 0 12px 32px -16px rgba(1, 28, 53, 0.14)",
        lift: "0 2px 4px rgba(1, 28, 53, 0.05), 0 24px 48px -20px rgba(1, 28, 53, 0.22)",
        float: "0 8px 40px -12px rgba(1, 28, 53, 0.28)",
        mint: "0 8px 32px -12px rgba(54, 206, 193, 0.45)",
        inset: "inset 0 1px 0 rgba(255, 255, 255, 0.06)",
      },
      maxWidth: {
        shell: "1280px",
        wide: "1440px",
        prose: "68ch",
      },
      spacing: {
        section: "clamp(4.5rem, 9vw, 8.5rem)",
        "section-sm": "clamp(3rem, 6vw, 5rem)",
      },
      letterSpacing: {
        eyebrow: "0.16em",
      },
      transitionTimingFunction: {
        brand: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--accordion-height)", opacity: "1" },
        },
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.9)", opacity: "0.7" },
          "70%": { transform: "scale(1.6)", opacity: "0" },
          "100%": { transform: "scale(1.6)", opacity: "0" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.6s cubic-bezier(0.22, 1, 0.36, 1) both",
        marquee: "marquee 46s linear infinite",
        "pulse-ring": "pulse-ring 2.4s cubic-bezier(0.22, 1, 0.36, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
